In [2]:
pip install numpy

In [3]:
import numpy as np

In [4]:
np.mean([1,4,3,5,3,5,3])

3.4285714285714284

In [5]:
np.median([1,4,3,5,3,5,3])

3.0

In [6]:
print(np.__version__)

1.26.4


In [ ]:
np.average

# Array

In [7]:
l = [1,2,3,4,5]

In [8]:
l

[1, 2, 3, 4, 5]

In [9]:
type(l)

list

In [10]:
d1 = np.array([1,2,3,4])

In [11]:
d1

array([1, 2, 3, 4])

In [13]:
d1.ndim

1

In [14]:
d2 = np.array([[1,2,3], [4,5,6]])

In [15]:
d2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
d2.ndim

2

In [17]:
d3 = np.array([[[1,2,3,4], [1,2,3,4],[10,20,30,40]]])

In [18]:
d3

array([[[ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [10, 20, 30, 40]]])

In [19]:
d3.ndim

3

In [20]:
np.random.randint(10,50,5)

array([47, 39, 40, 38, 35])

In [21]:
np.random.rand(3,2)

array([[0.56564625, 0.7878882 ],
       [0.65183364, 0.4458269 ],
       [0.91727191, 0.75580844]])

In [22]:
np.random.randn(2,2,3)

array([[[-0.84132799,  1.69208151,  1.8931296 ],
        [-0.86645913, -0.81232408, -0.89277135]],

       [[ 1.27909413,  0.54397106, -0.7598112 ],
        [ 2.16319281, -1.13453689,  1.92832416]]])

In [23]:
np.random.randint(1,6,1)

array([4])

In [24]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [25]:
import pandas as pd